### ISSUE TITLE
[iOS 15] The app is crashing when accessing to keychain

### ISSUE THREAD

**Issue by vladyslav-iosdev** [WalletConnect-Labs/WalletConnectSwiftV2#151] opened 2021-11-12 11:14 UTC
<img width="1381" alt="Screenshot 2021-11-12 at 13 12 15" src="https://user-images.githubusercontent.com/55975226/141458220-98cdc2c9-4609-48f7-9bec-220b8c522970.png">

**Comment by MisterVants** [comment] 2021-11-12 20:19
Did you catch any errors when adding (or getting) the key from the `KeychainStorage` before getting to the point of this crash?

**Comment by chadyj** [comment] 2021-12-02 13:27
@vladyslav-iosdev we believe this is fixed now. Would you mind trying to reproduce?

**Comment by vladyslav-iosdev** [comment] 2021-12-04 14:07
Thx a lot, i'l check and let u know.

**Comment by vladyslav-iosdev** [comment] 2021-12-04 14:18
@chadyj  For me the crash is still exists. That is happens when we open the app again. The method `didReceive(sessionProposal:)` get called automatically and we trying to connect to existing session.
here is some screen shots of logs:
<img width="332" alt="Screenshot 2021-12-04 at 16 13 52" src="https://user-images.githubusercontent.com/55975226/144712780-42bcdd3e-83b3-4da6-8b28-2862ae7b89a2.png">
<img width="1329" alt="Screenshot 2021-12-04 at 16 13 36" src="https://user-images.githubusercontent.com/55975226/144712782-f57f063d-f449-4b03-996c-ee402f1d0c1e.png">
<img width="1244" alt="Screenshot 2021-12-04 at 16 17 40" src="https://user-images.githubusercontent.com/55975226/144712822-9d56d556-b396-41aa-b04f-c2f4321a6147.png">

**Comment by llbartekll** [comment] 2021-12-06 09:42
hey @vladyslav-iosdev to me it looks like the code that you are building does not contain the fix, could you try to build last commit c8f9d53 on master branch?

**Closed** 2022-01-12 14:18 UTC
