### ISSUE TITLE
Resolve lost subscription issue

### ISSUE THREAD

**Issue by llbartekll** [WalletConnect-Labs/WalletConnectSwiftV2#58] opened 2021-09-20 09:25 UTC
when testing two swift relay A&B instances over staging server sometimes one relay A never receives subscription even though it is subscribing on related topic and relay B publishes a messages.

![Screenshot 2021-09-17 at 10 34 52](https://user-images.githubusercontent.com/25840476/133992769-c0cb0701-c7ff-4b14-a13e-f2ecaa56a533.png)

![Screenshot 2021-09-17 at 10 35 07](https://user-images.githubusercontent.com/25840476/133992788-50c784d1-94a8-4efe-b266-82890b7b4cfa.png)

**Comment by llbartekll** [comment] 2021-10-01 13:24
we do not experience it in "happy flow" so I remove it from milestone and we can examine it later

**Comment by chadyj** [comment] 2021-12-02 14:20
Couldn't reproduce this.  Closing.

**Closed by chadyj** 2021-12-02 14:20 UTC
